
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.run]
command = "trunk"
args = ["serve"]

[tasks.css]
command = "npx"
args = ["tailwindcss", "-i", "src/input.css", "-o", "src/tailwind.css"]

[tasks.dev]
dependencies = [
	"format",
	"css",
	"run",
	]
